name: ml
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - jupyter
    - keras
    - theano
    - pip:
        - https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.4.0-py3-none-any.whl
